name: Deploy Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ./MyFunctionApp/MyFunctionApp.csproj

      - name: Build
        run: dotnet build --configuration Release ./MyFunctionApp/MyFunctionApp.csproj

      - name: Run tests
        run: dotnet test --no-build --verbosity normal ./MyFunctionApp/MyFunctionApp.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output ./MyFunctionApp/bin/Release/net8.0/publish ./MyFunctionApp/MyFunctionApp.csproj

      - name: Verify Publish Directory
        run: ls -al ./MyFunctionApp/bin/Release/net8.0/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'waqqlyapp'
          package: './MyFunctionApp/bin/Release/net8.0/publish'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
