name: Azure Functions Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ./MyFunctionApp/MyFunctionApp.csproj

      - name: Build
        run: dotnet build --configuration Release ./MyFunctionApp/MyFunctionApp.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output ./MyFunctionApp/publish ./MyFunctionApp/MyFunctionApp.csproj

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'waqqlyapp'
          package: './MyFunctionApp/publish'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
